# Stage priorities
stages:
  - build
  - test

# Job 1: config test, file creation
create_file:
  image: ubuntu:latest
  stage: build
  script:
    - echo "This is a test file created by GitLab CI/CD pipeline."
    - mkdir build
    - touch build/test_file.txt
    - echo "File created successfully."
  artifacts:
    paths:
      - build/

# Job 2: test if the file has got created or not
test_file:
  image: ubuntu:latest
  stage: test
  script:
    - echo "test started"
    - test -f build/test_file.txt
    - echo "test completed, file existence checked."